[package]
name = "lunarjson"
description = ["A JSON formatter module for LunarDB"]
authors = ["Kazooki123"]
keywords = ["json", "database", "index", "module"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0"
