name: Publish to Homebrew

on:
  push:
    tags:
      - 'v0.1.6' 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: sudo apt-get install -y g++ liblua5.4-dev libpqxx-dev

      - name: Compile LunarDB
        run: |
          g++ -std=c++17 main.cpp cache.cpp saved.cpp sql.cpp module.cpp hashing.cpp \
          -I/usr/include/lua5.4 -llua5.4 -lpqxx -lpq -o bin/lunar

      - name: Create a release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/lunar

      - name: Update Homebrew Formula
        run: |
          SHA256=$(sha256sum bin/lunar | awk '{ print $1 }')
          sed -i "s/{{SHA256}}/$SHA256/" lunardb.rb
          git add lunardb.rb
          git commit -m "Update formula with new version"
          git push origin main

      - name: Publish Homebrew Tap
        run: |
          brew tap yourusername/lunardb
          brew install lunar
