name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Cpp (C++ / C)
      uses: aminya/setup-cpp@v0.44.0
      with:
        compiler: gcc

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make g++

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      working-directory: ./build
      run: ctest

    - name: Run executable
      run: ./build/src/your_executable_name_here
